# Generated by Django 3.0.5 on 2021-03-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gql_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('units', models.IntegerField()),
                ('sales', models.IntegerField()),
                ('date_sold', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Hola',
        ),
    ]
