# Generated by Django 3.0.5 on 2021-03-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('units', models.IntegerField(max_length=100)),
                ('sales', models.IntegerField(max_length=100)),
                ('date_sold', models.CharField(max_length=100)),
            ],
        ),
    ]
